server:
  port: 8083

spring:
  application:
    name: INVENTORY-SERVICE

  datasource:
    url: jdbc:postgresql://db-inventory:5432/inventory
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

product:
  url: http://product-service:8082

eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
