server:
  port: 8082

spring:
  application:
    name: PRODUCT-SERVICE
  datasource:
    url: jdbc:postgresql://db-product:5432/product
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  doc:
    swagger-ui:
      path: /swagger-ui.html
    api-docs:
      path: /api-docs


minio:
  url: http://minio:9002
  access:
    name: 3C96HQCAU3MG3T4ABWUD
    secret: h6npXEt+4+eOuPRyq1uRMYKOP5r9SNxtOEJ3RILn
  bucket:
    name: products

eureka:
  instance:
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

gateway:
  url: http://api-gateway:8080