server:
  port: 8082

spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
          autoCreateTopics: true
      function:
        definition: sendProductMessage;sendCartMessage;sendInventoryMessage
      bindings:
        sendProductMessage-out-0:
          destination: product-topic
        sendCartMessage-out-0:
          destination: cart-topic
        sendInventoryMessage-out-0:
          destination: inventory-topic
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  application:
    name: PRODUCT-SERVICE
  datasource:
    url: jdbc:postgresql://localhost:5433/product
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  doc:
    swagger-ui:
      path: /swagger-ui.html
    api-docs:
      path: /api-docs

minio:
  url: http://localhost:9002
  access:
    name: 3C96HQCAU3MG3T4ABWUD
    secret: h6npXEt+4+eOuPRyq1uRMYKOP5r9SNxtOEJ3RILn
  bucket:
    name: products

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/

gateway:
  url: http://localhost:8080
