server:
  port: 8085

spring:
  application:
    name: PAYMENT-SERVICE

  datasource:
    url: jdbc:postgresql://localhost:5436/payment
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

product:
  url: http://localhost:8082

inventory:
  url: http://localhost:8083

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://${eureka.instance.hostname}:8761/eureka/
